Enable animals to spawn children
Buffes/Ecosystem pull request #101
Opened 2020-04-14 15:16 UTC by emmanir

2020-04-14 16:43 UTC, Slarvsylt approved these changes

2020-04-14 16:51 UTC, gimme requested changes

2020-04-14 16:51 UTC, G1mmicK commented on Assets/Scripts/Genetics/DNA.cs
> +                if (parent1.genes[i].GetType() != parent2.genes[i].GetType()) throw ParentGeneMismatchException;
```suggestion
                if (parent1.genes[i].Type.GetType() != parent2.genes[i].Type.GetType()) throw ParentGeneMismatchException;
```

2020-04-14 16:51 UTC, G1mmicK commented on Assets/Scripts/Genetics/DNA.cs
> +            List<Gene> genes = new List<Gene>();
```suggestion
            List<Gene> genes = new List<Gene>(amount);
```

2020-04-15 11:05 UTC, gimme approved these changes

2020-04-15 11:06 UTC, merged