Flee only when believed to be noticed
Buffes/Ecosystem pull request #138
Opened 2020-04-22 08:00 UTC by emmanir

Prey doesn't flee from predators if they believe they are not seen

2020-04-24 00:28 UTC, gimme requested changes

2020-04-24 00:28 UTC, G1mmicK commented on Assets/Scripts/ECS/Targeting/FindSystems/FindPredatorSystem.cs
> +                    if (!Utilities.IntersectsVision(position.Value,targetPosition,targetRotation,vision)) continue; // Predator not looking at prey
"vision" som används här är bytets vision och inte rovdjurets. Det kanske räcker med att kolla om rovdjurets rotation är mindre än 90 grader från bytet.

2020-04-24 05:50 UTC, emmanir commented on Assets/Scripts/ECS/Targeting/FindSystems/FindPredatorSystem.cs
> +                    if (!Utilities.IntersectsVision(position.Value,targetPosition,targetRotation,vision)) continue; // Predator not looking at prey
Jag tänkte att bytet inte vet vad rovdjuret ser och därför använder sina egna erfarenheter att utgå ifrån?

2020-04-24 10:47 UTC, G1mmicK commented on Assets/Scripts/ECS/Targeting/FindSystems/FindPredatorSystem.cs
> +                    if (!Utilities.IntersectsVision(position.Value,targetPosition,targetRotation,vision)) continue; // Predator not looking at prey
Det är generellt sett inte bra om system beror på fler saker än de behöver. Nu kan ett djur bara hitta rovdjur om det har en vision-komponent vilket det inte är säkert att alla djur har (implementationsdetalj). Även om blinda djur alltid skulle ha en vision-komponent med range = 0 så kommer de aldrig att upptäcka en predator som rör sig mot dem i det här fallet.

Föreställ dig bytesdjur med olika vinklar på synfältet. Om det är större än 180° skulle den fortfarande blir rädd för rovdjur som rör sig bort. Om det är mindre än 180° kan det förekomma frames där bytet inte upptäcker rovdjuret (trots att det är på väg i shortest path till bytet) p.g.a. att rovdjurets path checkpoint just då är t.ex. i diagonalen mellan två tiles.

2020-04-28 07:46 UTC, gimme approved these changes

2020-04-28 07:46 UTC, merged