Baby animals
Buffes/Ecosystem pull request #154
Opened 2020-04-24 09:48 UTC by Buffes

Added behaviour for baby animals. 

- Scale increases with age.
As animals age they go from a smaller scale to full size. To make this work the animals need a CompositeScale component. This gets added automatically by unity if the scale of the transform is anything else than 1. This is why the animal prefab's entities now have 0.99 scale. The MaturingSystem sets it to 1 for adults however.

- Changed behaviour for young animals.
They now follow their parent and take food and water from them if they get hungry/thirsty. The parent is determined by the ImprintingSystem, but it will almost always be the animal which gave birth to them. 

Lifespan no longer has GenerateAuthoringComponent. There is now an AgeAuthoring which contains info about lifespan and age.

2020-04-24 13:04 UTC, gimme requested changes

2020-04-24 13:04 UTC, gimme commented on Assets/Prefabs/Animals/Animal.prefab
> +  Lifespan: 0
```suggestion
  Lifespan: 20
```
Kanske bra att ha ett default värde

2020-04-24 13:04 UTC, gimme commented on Assets/Prefabs/Food/Food.prefab
> +  Lifespan: 0
```suggestion
  Lifespan: 1
```
Igen, default värde

2020-04-24 13:04 UTC, gimme commented on Assets/Scenes/Main_scene.unity
> -  m_PrefabAsset: {fileID: 0}
Är det några nödvändiga ändringar i main scene? Ser ut som att det kan bli lite konflikter

2020-04-24 13:04 UTC, gimme commented on Assets/Scripts/Attributes/Animal.cs
> +
Jättebra men kanske borde göras internt i StateMachine?

2020-04-24 13:04 UTC, gimme commented on Assets/Scripts/ECS/Hybrid/NeedsStatus.cs
> +            EntityManager.SetComponentData(ParentEntity, new HungerData { Hunger = cur - value });
'cur' är barnets hunger och används nu för att sätta förälderns.

2020-04-24 13:04 UTC, gimme commented on Assets/Scripts/ECS/Targeting/FindSystems/FindMateSystem.cs
> +                .WithAll<Adult>()
```suggestion
```
Barn ska ju aldrig gå in i ett state för att leta efter mate men jag ser ingen anledning till att göra de inkapabla.

2020-04-24 13:14 UTC, Buffes commented on Assets/Scripts/Attributes/Animal.cs
> +
Jag tänkte att eftersom transitions till samma state är något som tillåts i de flesta state machines, så är det bättre att ha det utanför. Det spelar ingen roll för mig egentligen.

2020-04-24 13:19 UTC, Buffes commented on Assets/Scenes/Main_scene.unity
> -  m_PrefabAsset: {fileID: 0}
nä, tar bort det

2020-04-26 11:09 UTC, G1mmicK commented on Assets/Scripts/Attributes/Animal.cs
> +
Låter rimligt

2020-04-26 11:15 UTC, gimme requested changes

2020-04-26 11:15 UTC, G1mmicK commented on Assets/Scripts/ECS/Hybrid/NeedsStatus.cs
> +            float parentValue = EntityManager.GetComponentData<ThirstData>(parentEntity).Thirst;
```suggestion
            float parentValue = EntityManager.GetComponentData<HungerData>(parentEntity).Hunger;
```

2020-04-26 23:36 UTC, gimme approved these changes

2020-04-27 09:07 UTC, merged