Bravery component
Buffes/Ecosystem pull request #168
Opened 2020-04-28 17:16 UTC by Slarvsylt

Added a component for bravery which means that an animal can ignore threats if it is hungry/thirsty enough.

2020-04-28 18:44 UTC, Buffes requested changes

2020-04-28 18:44 UTC, Buffes commented on Assets/Scripts/Attributes/Animal.cs
> +                    }
Om man byter här skulle barn kunna gå in i hunger eller thirst state, vilket det inte är meningen att de ska göra. Det borde väl funka att inte ha denna else-satsen alls? Djuret flyr inte, och senare kollar den om den hittat mat eller vatten som vanligt. 

Annars skulle man kunna lägga till att den bara kollar efter mat och vatten om djuret är vuxet, typ `LookForFood(!isAdult() && ...)` etc.

2020-04-29 16:27 UTC, Buffes requested changes

2020-04-29 16:27 UTC, Buffes commented on Assets/Scripts/Attributes/Animal.cs
>                  ChangeState(this.fleeState);
Borde inte denna `ChangeState(this.fleeState)` vara inom else? Går den inte alltid in i flee state här om det är utan else?

2020-05-01 07:55 UTC, Slarvsylt commented on Assets/Scripts/Attributes/Animal.cs
>                  ChangeState(this.fleeState);
Lägger till en else

2020-05-01 08:32 UTC, Buffes approved these changes

2020-05-01 08:32 UTC, merged