Mesh terrain
Buffes/Ecosystem pull request #180
Opened 2020-05-06 13:04 UTC by Buffes

Added a mesh mode for the terrain. 

GameZone now contains two modes for terrain creation. Tilemap is the one currently in master, and Mesh uses a mesh instead, providing height variation and easy ability to customize visuals with shaders. 

The logic is still entirely based on 2D. The only adjustments are to make sure entities are placed on the mesh and not underneath it.

2020-05-08 09:21 UTC, gimme requested changes

2020-05-08 09:21 UTC, gimme commented on Assets/Gameplay/FoodTypes/Meat/Chicken.asset
> +  m_Name: Chicken
```suggestion
  m_Name: Rabbit
```

2020-05-08 09:21 UTC, gimme commented on Assets/Gameplay/FoodTypes/Meat/Lion.asset
> +  m_Name: Lion
```suggestion
  m_Name: Fox
```

2020-05-08 09:21 UTC, gimme commented on Assets/Scripts/Grid/GameZone.cs
> +                    tiles[x,y] = NoiseMap[x,y] > Regions[0].Height ? landIndex : waterIndex;
Det är sällan bra att använda en hårdkodad index i en array. Det här kräver att vatten alltid är den första regionen. Vatten borde antingen hanteras likadant som vilken annan TerrainType som helst eller, om det inte går (för att vatten är för unik), vara i en egen variabel utanför Regions-array:en.

2020-05-08 09:21 UTC, gimme commented on Assets/Scripts/Spawner/PrefabSpawner.cs
> +                    spawnPos.y = GameZone.NoiseMap[grid.GetGridPositionFromIndex(n).x, grid.GetGridPositionFromIndex(n).y];
Varför är det annorlunda här mot hur FruitSpawner hittar marknivån? Noise-map:ens implementationsdetaljer borde i alla fall inte exponeras. GroundCollisionSystem.GetGroundLevel kanske inte heller är den bästa i det här sammanhanget eftersom det känns som att det egentligen är GameZone man borde hämta den informationen ifrån.

2020-05-08 09:21 UTC, G1mmicK commented on Assets/Scripts/Grid/ScenaryToTilemap.cs
> +            spawnPos.y = GameZone.NoiseMap[row, col];
Samma grej som PrefabSpawner

2020-05-08 09:21 UTC, G1mmicK commented on Assets/Scenes/Main_scene.unity
> +      objectReference: {fileID: 0}
Gör hellre ändringar på Main_Camera-prefab:en än i scenen (zoom speed)

2020-05-08 12:26 UTC, Buffes commented on Assets/Scripts/Spawner/PrefabSpawner.cs
> +                    spawnPos.y = GameZone.NoiseMap[grid.GetGridPositionFromIndex(n).x, grid.GetGridPositionFromIndex(n).y];
Tycker du att hela GetGroundLevel ska flyttas till GameZone? Det känns som att GameZone ansvarar för för mycket redan.

2020-05-08 12:27 UTC, Buffes commented on Assets/Scripts/Grid/GameZone.cs
> +                    tiles[x,y] = NoiseMap[x,y] > Regions[0].Height ? landIndex : waterIndex;
La in en dropdown där man väljer vilken region som är vattennivån nu

2020-05-08 19:27 UTC, G1mmicK commented on Assets/Scripts/Spawner/PrefabSpawner.cs
> +                    spawnPos.y = GameZone.NoiseMap[grid.GetGridPositionFromIndex(n).x, grid.GetGridPositionFromIndex(n).y];
GameZone ansvarar redan för den delen i och med att du hämtar den informationen från GameZone.NoiseMap. Jag menar bara att PrefabSpawner inte ska behöva känna till någon noise map utan att den använder någon metod som typ GetGroundLevel(position).

2020-05-08 19:41 UTC, gimme requested changes

2020-05-08 19:41 UTC, G1mmicK commented on Assets/Scripts/Grid/GameZone.cs
> +        // }
```suggestion
```

2020-05-08 19:41 UTC, G1mmicK commented on Assets/Scripts/Grid/GameZone.cs
> +                    Debug.Log(Regions[WaterThresholdIndex].Height);
```suggestion
```

2020-05-10 13:01 UTC, gimme approved these changes

2020-05-10 13:01 UTC, merged