Hunger thirst systems
Buffes/Ecosystem pull request #32
Opened 2020-03-13 16:40 UTC by Slarvsylt

System for thirst and hunger. When thirst/hunger reaches 1.0f a DeathEvent-component is attached to the animal. Also added a hybrid class for getting and decreasing hunger/thirst-levels.

2020-03-13 18:06 UTC, gimme requested changes

2020-03-13 18:06 UTC, gimme commented on Assets/Scripts/ECS/Animal/Needs/ThirstSystem.cs
> +            throw new NotImplementedException();
```suggestion
            m_EndSimulationEcbSystem.AddJobHandleForProducer(Dependency);
```

2020-03-13 18:06 UTC, gimme commented on Assets/Scripts/ECS/Animal/Needs/HungerSystem.cs
> +            throw new NotImplementedException();
```suggestion

            m_EndSimulationEcbSystem.AddJobHandleForProducer(Dependency);
```

2020-03-13 18:06 UTC, gimme commented on Assets/Scripts/ECS/Animal/Needs/HungerSystem.cs
> +                if(hungerData.Hunger <= 0.0f)
```suggestion
                if(hungerData.Hunger > 1.0f)
```

2020-03-13 18:06 UTC, G1mmicK commented on Assets/Scripts/ECS/Hybrid/NeedsStatus.cs
> +
```suggestion
```

2020-03-13 18:06 UTC, G1mmicK commented on Assets/Scripts/ECS/Hybrid/NeedsStatus.cs
> +        }
The decrease methods can reduce the values below 0. Is this intended?

2020-03-13 18:15 UTC, gimme reviewed
I think that hunger/thirst would be easier to understand as like a "hunger bar" that **decreases** as you get **more** hungry.

I also think that it would be better if it was a number from 0 to infinity instead of 0 to 1 as that would work well with different max hungers for different animals.

2020-03-14 15:42 UTC, Slarvsylt commented
I comply with your requests.

2020-03-14 16:50 UTC, gimme approved these changes

2020-03-14 16:51 UTC, merged