Animal growth
Buffes/Ecosystem pull request #52
Opened 2020-03-25 14:28 UTC by Buffes

Animals now have an age component which increments over time. Their age of death is determined by the lifespan component, which acts as an average lifespan for calculating the actual age of death.

2020-03-27 14:33 UTC, gimme requested changes

2020-03-27 14:33 UTC, gimme commented on Assets/Scripts/ECS/Animal/AgeOfDeathData.cs
> +    [GenerateAuthoringComponent]
```suggestion
```
För att undvika förvirring, om den här komponenten alltid läggs till och skrivs över av AgeOfDeathSystem så borde den inte ha en authoring component.

2020-03-27 14:33 UTC, gimme commented on Assets/Samples/Sample1_HybridECS/Prefabs/Rabbit.prefab
> +  needsStatus: {fileID: 0}
```suggestion
```
Det här är fixat i master och kommer antagligen skapa en merge conflict.

2020-03-27 14:33 UTC, gimme commented on Assets/Samples/Sample1_HybridECS/Prefabs/Rabbit.prefab
> +  Age: 0
Jag kan inte se vilken den första av dessa komponenter är, men age är något som alla djur ska ha så det borde läggas till på Animal prefab:en istället för Rabbit.

2020-03-28 14:25 UTC, Buffes commented on Assets/Scripts/ECS/Animal/AgeOfDeathData.cs
> +    [GenerateAuthoringComponent]
Just det ja

2020-03-28 15:27 UTC, Buffes commented on Assets/Samples/Sample1_HybridECS/Prefabs/Rabbit.prefab
> +  Age: 0
Jag gjorde så AgeData läggs till automatiskt nu, så animal behöver bara Lifespan, vilket jag la till på prefaben.

2020-03-28 16:09 UTC, gimme approved these changes

2020-03-28 16:09 UTC, merged