Resource regeneration
Buffes/Ecosystem pull request #53
Opened 2020-03-25 17:36 UTC by KasperHall

2020-03-26 09:24 UTC, KasperHall commented
noticed bug where code gets stuck when there's no space left to spawn on, trying to reslove it now

2020-03-27 17:15 UTC, KasperHall commented
I did a simple fix where it tries to randomize a suitable spawning location, after ~700 attempts it just skips the spawning that time. Is this a good enough fix? We should never reach the point of a grid with no space left either way.. :D

2020-03-27 23:51 UTC, gimme requested changes
Det är en del duplicering i koden. Du kanske kan bryta ut gemensam funktionalitet i metoder som fungerar för både grass och seaweed.

2020-03-27 23:51 UTC, gimme commented on Assets/Scripts/Spawner/ResourceReg.cs
> +            searchTime += Time.deltaTime;
Time.deltaTime är hur många sekunder som har gått sedan förra frame:en. Det blir konstigt om man lägger till den flera gånger under samma frame (hela den här loopen körs alltid i en frame).

Istället för 'max tid' kanske du vill använda 'max antal försök'.

2020-03-27 23:51 UTC, G1mmicK commented on Assets/Scripts/Spawner/ResourceReg.cs
> +    public static List<int> occupiedWaterSpace = new List<int>();
```suggestion
    private List<int> occupiedWaterSpace = new List<int>();
```
Ska den vara public static?

2020-03-27 23:51 UTC, G1mmicK commented on Assets/Scripts/Spawner/ResourceReg.cs
> +                occupiedWaterSpace.Add(n);
Efter att en seaweed har spawnats i en tile så kan ingen seaweed spawnas där någonsin igen, även efter den ätits upp. Till slut kan det inte spawna något mer i vattnet.

2020-03-27 23:51 UTC, G1mmicK commented on Assets/Scripts/Spawner/ResourceReg.cs
> +                o.transform.position = new Vector3(x, 1, y);
Instantiate har en overload där du kan säga vilken position den ska spawnas på.

2020-03-27 23:51 UTC, G1mmicK commented on Assets/Scripts/Spawner/ResourceReg.cs
> +            int y = (n - x) / GameZone.tiles.GetLength(0);
```suggestion
            int x = n % tiles.GetLength(0);
            int y = (n - x) / tiles.GetLength(0);
```

2020-03-27 23:51 UTC, G1mmicK commented on Assets/Scripts/Spawner/ResourceReg.cs
> +                grid[n] = false;
```suggestion
```
Ska man verkligen inte kunna gå på tiles med gräs i?

2020-03-29 14:47 UTC, KasperHall commented on Assets/Scripts/Spawner/ResourceReg.cs
> +    public static List<int> occupiedWaterSpace = new List<int>();
Tanken var att göra den public static för att kunna ta bort tilens nummer från listan när sjögräset blir uppätet, då skulle problemet att saker inte kan spawna där andra saker har spawnat innan lösas. Är detta en okej lösning?

2020-03-29 14:49 UTC, KasperHall commented on Assets/Scripts/Spawner/ResourceReg.cs
> +                grid[n] = false;
Tänkte gräs som ett träd eller en sten, du har helt rätt att dom borde kunna gå över gräset

2020-03-29 21:21 UTC, G1mmicK commented on Assets/Scripts/Spawner/ResourceReg.cs
> +    public static List<int> occupiedWaterSpace = new List<int>();
Jag tycker inte det. Det här problemet ligger lite utanför scopet av den här regeneration-featuren. Vi kanske får diskutera det i gruppen.

Om vi vill kunna se om en ruta är upptagen så borde det skötas utanför det här systemet och fungera för alla typer av object som kan placeras i världen. Man skulle kunna ha en array med alla placerade object (träd, gräs, buskar, etc.), både walkable och unwalkable. En annan lösning skulle kunna vara att använda colliders för att inte spawna saker i varandra (typ en collider check där man tänkt spawna).

2020-03-29 21:55 UTC, gimme reviewed
Det blir svårt att lösa 'occupied space'-problemet från den här branchen. Jag skulle säga att det är bättre att bara låta de spawna på samma ställe för tillfället. Det borde inte blir något problem förutom att det inte ser snyggt ut.

2020-03-29 21:55 UTC, G1mmicK commented on Assets/Scripts/StateMachine/HungerState.cs
> +                ResourceReg.occupiedSpace.Remove(nextTarget);
Det här är inte så bra att göra. Djuret borde inte sköta grid-logiken.

2020-03-29 21:55 UTC, G1mmicK commented on Assets/Scripts/Spawner/ResourceReg.cs
> +                    (!grid[n] && tiles[x, y] < 34 && !occupiedSpace.Contains(new Vector3(x, 1, y)) && plant == seaweed))
Vector3 består av floats, så på grund av floating-point imprecision kan du inte hitta dem med hjälp av 'Contains'.

2020-03-30 19:13 UTC, gimme approved these changes

2020-03-30 19:13 UTC, merged