Birth event
Buffes/Ecosystem pull request #58
Opened 2020-03-27 10:57 UTC by Slarvsylt

System for giving birth. Changes in the reproductionSystem as well.

2020-03-27 16:03 UTC, gimme requested changes

2020-03-27 16:03 UTC, gimme commented on Assets/Scripts/ECS/Reproduction/BirthSystem.cs
> +                baby.InitDNA(DNA.InheritedDNA(dna, pregnancyData.DNAfromFather)); // Initialize the baby's DNA
BirthEvent borde väl consumas här?

2020-03-27 16:03 UTC, gimme commented on Assets/Scripts/ECS/Animal/PregnancyData.cs
> +        public DNA DNAfromFather;
Jag föreslår att pregnancy data håller fostrets nya DNA istället för pappans.

2020-03-27 16:03 UTC, gimme commented on Assets/Scripts/ECS/Reproduction/ReproductionEventSystem.cs
> +                EntityManager.RemoveComponent<ReproductionEvent>(entity);
Sänk sexual urge här?

2020-03-27 16:03 UTC, gimme commented on Assets/Scripts/ECS/Animal/GestationData.cs
> +        public float TimeSinceFertilisation;
Den här temporära tidshållningen borde vara i PregnancyData istället.

2020-03-27 16:03 UTC, gimme commented on Assets/Scripts/ECS/Reproduction/GestationSystem.cs
> +                , ref GestationData gestationData) =>
Det här systemet körs varje frame på alla entities med GestationData. Jag tolkade det som att GestationData är något som alla djur har från början (genom authoring component). Det betyder att graviditetstiden börjar ticka med en gång istället för när djuret blir gravid.

2020-03-27 16:03 UTC, gimme commented on Assets/Scripts/ECS/Reproduction/GestationSystem.cs
> +                    commandBuffer.AddComponent(entityInQueryIndex, entity, new BirthEvent());
TimeSinceFertilisation reset:as aldrig vilket gör att det blir fel andra gången ett djur blir gravid.

2020-03-27 16:03 UTC, gimme commented on Assets/Scripts/ECS/Reproduction/ReproductionEventSystem.cs
>                  if(sexData.Sex == Sex.Female)
Kanske borde kolla att djuret inte redan är gravid här också

2020-03-30 20:29 UTC, gimme requested changes

2020-03-30 20:29 UTC, G1mmicK commented on Assets/Scripts/ECS/Reproduction/ReproductionEventSystem.cs
> +                if(sexData.Sex == Sex.Female && EntityManager.HasComponent<PregnancyData>(entity))
```suggestion
                if(sexData.Sex == Sex.Female && !EntityManager.HasComponent<PregnancyData>(entity))
```

2020-03-30 20:29 UTC, G1mmicK commented on Assets/Scripts/ECS/Reproduction/BirthSystem.cs
> +
```suggestion
                EntityManager.RemoveComponent<PregnancyData>(entity);

```

2020-03-30 20:29 UTC, G1mmicK commented on Assets/Scripts/ECS/Reproduction/BirthSystem.cs
> +                EntityManager.RemoveComponent<BirthEvent>(entity);
```suggestion
                EntityManager.RemoveComponent<BirthEvent>(entity);
                EntityManager.RemoveComponent<PregnancyData>(entity);
```

2020-03-30 20:29 UTC, G1mmicK commented on Assets/Scripts/ECS/Reproduction/ReproductionEventSystem.cs
> +                if(sexData.Sex == Sex.Female && EntityManager.HasComponent<PregnancyData>(entity))
```suggestion
                if(sexData.Sex == Sex.Female && !EntityManager.HasComponent<PregnancyData>(entity))
```

2020-04-01 10:06 UTC, gimme approved these changes

2020-04-01 10:07 UTC, merged