Unreachable positions dynamic buffer
Buffes/Ecosystem pull request #68
Opened 2020-03-31 18:42 UTC by Buffes

Adds a dynamicBuffer of unreachable positions to the animals. If pathfinding cannot find a path, the target is added to the unreachable buffer, and the find systems will ignore entities in those positions in the future. The unreachable position also has a timestamp that is used to remove it after a set time.

This fixes the problem of entities getting stuck if their closest target is not reachable. 

Made an authoring component for UnreachablePosition and added PathElement to it, so you can just add PathfindingAuthoring to your prefab to get those two buffers.

2020-04-02 13:15 UTC, gimme requested changes
Vad är det för ändringar på prefabs:en? Jag förstår inte varför FoxMeat, RabbitMeat, Fox och Rabbit ska ändras och varför frukterna tas bort.

Varför behöver du ändra på ECSHybridScene?

2020-04-02 13:15 UTC, gimme commented on Assets/Scripts/ECS/Movement/Pathfinding/PathfindingSystem.cs
> +            int z = (int)math.round(worldPosition.z);
```suggestion
            int x = (int)math.floor(worldPosition.x);
            int z = (int)math.floor(worldPosition.z);
```

2020-04-02 13:15 UTC, gimme commented on Assets/Scripts/ECS/Movement/Pathfinding/RemoveOldUnreachableSystem.cs
> +            }
```suggestion
            while (unreachablePositions.Length > 0)
            {
                double difference = now - unreachablePositions[0].Timestamp;
                if (difference < REMOVE_TIME) break;

                unreachablePositions.RemoveAt(0);
            }
```
Det blir lätt fel om man ändrar på listan som man itererar över. Om man tar bort på position i och sedan increment:ar i så skippar man ett element.

Eftersom alla element ligger i ordning (äldst först) behöver vi inte gå igenom alla. Vi kan pop:a början av listan tills vi når ett element som inte är tillräckligt gammalt och sedan avsluta loopen.

2020-04-02 13:15 UTC, G1mmicK commented on Assets/Scripts/ECS/Movement/Pathfinding/UnreachablePosition.cs
> +        public int2 Position;
Finns det något sätt att ha unreachable entity istället? Eller fungerar position bra?

2020-04-02 13:15 UTC, G1mmicK commented on Assets/Scripts/ECS/Targeting/Utilities.cs
> +            int z = (int)math.round(worldPosition.z);
```suggestion
            int x = (int)math.floor(worldPosition.x);
            int z = (int)math.floor(worldPosition.z);
```

2020-04-02 17:05 UTC, Buffes commented on Assets/Scripts/ECS/Movement/Pathfinding/PathfindingSystem.cs
> +            int z = (int)math.round(worldPosition.z);
Tror det ska vara round och inte floor eftersom GameZone börjar på x: -0.5 och z: -0.5. Då hamnar mitten på varje ruta på heltalen, så något med t.ex. position 9.7 i världen ser ut att vara på ruta 10, inte 9.

Frukterna var att jag tog bort colliders för dem, det kändes onödigt. Blev att djuren liksom gled över frukten. 

Ska kolla om det är något nödvändigt i ECSHybridScene och Fox, rabbit, och Meat

2020-04-02 17:10 UTC, Buffes commented on Assets/Scripts/ECS/Movement/Pathfinding/RemoveOldUnreachableSystem.cs
> +            }
Ja, jag tänkte på det felet också. Det är en bättre lösning.

2020-04-02 17:17 UTC, Buffes commented on Assets/Scripts/ECS/Movement/Pathfinding/UnreachablePosition.cs
> +        public int2 Position;
Pathfindingen vet inget om vilken entity targeten handlar om just nu. Den hanterar bara positioner på griden. Man skulle kunna lägga till en entity i MoveCommand, men det är vissa targets, t.ex. vatten, som inte har en associerad entity.

Vad är motivationen till att ha unreachable entity istället?

2020-04-03 07:28 UTC, G1mmicK commented on Assets/Scripts/ECS/Movement/Pathfinding/UnreachablePosition.cs
> +        public int2 Position;
Om ett djur jagar ett annat djur eller vill gå till en potentiell mate så kommer dess target byta position hela tiden. Så fort de rör sig en ruta så kommer pathfindingen att överväga den igen.

Även om de kan byta position flera gånger per sekund kan jag tänka mig att det inte påverkar performance så mycket eftersom vi ändå kommer att spara ganska många frames innan positionen ändras.

Jag reagerade mest på att det var 60 sekunders timeout på onåbara rutor när rutorna ibland bara är relevant i en halv sekund. Jag är ändå nöjd med din lösning.

2020-04-03 07:30 UTC, gimme approved these changes

2020-04-03 07:43 UTC, Buffes commented on Assets/Scripts/ECS/Movement/Pathfinding/UnreachablePosition.cs
> +        public int2 Position;
Ja, 60 sekunder är inget jag är säker på som optimalt. Det är ganska olika hur länge positionerna är relevanta som unreachable. Om target är utanför range kan det räcka med att entityn rör sig lite, men om den är på en ö på andra sidan vatten kommer de alltid vara unreachable

2020-04-03 09:30 UTC, merged