Species separated death causes
Buffes/Ecosystem pull request #82
Opened 2020-04-10 06:38 UTC by emmanir

DeathStatsSystem now separates different animals stats

2020-04-10 09:20 UTC, gimme requested changes

2020-04-10 09:20 UTC, G1mmicK commented on Assets/ScriptableObjects/Gameplay/AnimalType.cs
> +        public Ecosystem.ECS.Animal.AnimalTypeNames Name;
Detta borde vara en string istället. Du kan tänka att djuren som skapas från AnimalType redan är som enums och de kommer alla ha unika namn vilket betyder att det är enklare att definiera namnet för varje djurtyp i inspectorn.

2020-04-10 09:20 UTC, G1mmicK commented on Assets/Scripts/ECS/Death/DeathStatsSystem.cs
> +        public DeathStats eagle;
Det här kan ersättas med en map (Dictionary) med namnet som nyckel. Då kommer du kunna eliminera koddupliceringen och sedan kunna lägga till hur många djur som helst utan att ändra på koden.

2020-04-10 09:23 UTC, gimme reviewed
Vad är det för ändringar på Lion.prefab, Chicken.prefab och Main_scene?

2020-04-12 13:50 UTC, emmanir commented
Ändringar på prefabs är att jag ändrat på siffrorna för synfält och liknande (för att rabbits inte konstant ska springa till kanten t.ex.), samt att jag ändrat siffror på ålder för att utföra testning (vilket borde vara tillbaka i senaste commiten). Main_scene råkade följa med, och förändringen är att den har en prefabSpawner

2020-04-12 17:16 UTC, gimme approved these changes

2020-04-12 17:16 UTC, merged