Visual cone debugging v2
Buffes/Ecosystem pull request #83
Opened 2020-04-10 07:10 UTC by SemlanChalmers

2020-04-10 09:36 UTC, gimme requested changes

2020-04-10 09:36 UTC, G1mmicK commented on Assets/Prefabs/Animals/Animal.prefab
> +  Range: 20
```suggestion
  Range: 0
```
Det här värdet används inte när djuret har base vision. Jag tror att det är större risk att man blandar ihop dem om det inte är 0 här.

2020-04-10 09:36 UTC, G1mmicK commented on Assets/Scripts/ECS/Debugging/VisionDebuggingSystem.cs
> +        }
```suggestion
```

2020-04-10 09:36 UTC, G1mmicK commented on Assets/Scripts/ECS/Debugging/VisionDebuggingSystem.cs
> +        private void UpdateMesh() {
```suggestion
```

2020-04-10 09:36 UTC, G1mmicK commented on Assets/Scripts/ECS/Reproduction/GestationSystem.cs
> +            }).Run();
Är detta verkligen nödvändigt?

2020-04-10 09:36 UTC, G1mmicK commented on Assets/EgyptMonsters.meta
> +  mainObjectFileID: 0
```suggestion
guid: f158fd0749fd2426a8a02adcaf3c89a5
folderAsset: yes
DefaultImporter:
  externalObjects: {}
```

2020-04-10 09:39 UTC, gimme reviewed
Jag vet inte vad du har gjort för ändringar i ECSHybridScene men jag låter dom gå igenom om det är avsiktligt.

2020-04-13 17:38 UTC, SemlanChalmers commented on Assets/Scripts/ECS/Reproduction/GestationSystem.cs
> +            }).Run();
Ingen aning, har inte jobbat med GestationSystem

2020-04-13 20:13 UTC, gimme approved these changes

2020-04-13 20:13 UTC, merged